sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Z4Mq9yGD0x1yGerHdjMEEuo0eOu9bcWh+FHZBhqulxa4HOGCj8U0/LOYmzLn1nCzDRvu/HBtczqhNj5ue5SDGc2X8ROt6ZlUVnhWSkCrO6tJGiFgA/G8TqIzjUTAUYJDk+1zsbuX6RUXklbRjTjnmDf0t6qg5ypWCiF1JwvHRvXuYINKJIaQvuRBqXf987eVz96vcfjFayVO1cw1WpvYDzcJwgsmuokGXsyXcJArsQf2mjbqixmZ75DbmddZhPN2fuMFqAp4wyY9gzTdJ05j9L8ltMLJpgAlYMwAeZnVWQ9tVinpSZkDXOrk9vO5EZPWN6WeNZbPcxPipkQKr5Wp7jsQ834WZA+QEuUshVjupIO9EQUs1c46DKvVG8Ocepfx3bvmBrTv9zuhZLzqSrZm94UpSpmsXzcjuQNXzSdfE2GQT+bUVQbJYPs/otEJpusCADgVQn+8AHZIu7P+9NWojLEyE2W0RxxMOTydOURZrKb2NAvs1iHFHtpjyjiCF1TNuEvJSrHmAXqARqJ1Ju18oraLfG1w2D1a9Ml8yRGZiVwHglBlDnuz4cc165L0ngPc1nwzzKwiYJOtuvZS5bHmXsqeVuZMMJMxMntu1fqVcwapU4lmN2p042cAdkpA3DJAR/mAgqo8HTPmu8EeBSdL2/uUvDZRZZkbZT7j+oZy4yw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Far-from-the-Madding-Crowd_27
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy